### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by ryanpavlick** [lianos/papers-bin#3]
papers.py does not convert the utf8 symbols which are not recognized by ASCII-only BibTex to Latex format.

For instance, dìaz should become d`{i}az.

There is a pre-existing python tool for detailing with this issue: http://code.activestate.com/recipes/252124-latex-codec/
It is licensed under PSF which is compatible with the GPL license of papers.py

**Comment by lianos** [comment]
Thanks, I'll have a look.
