### ISSUE TITLE
papers.py fails to open database.

### ISSUE THREAD

**Issue by mok0** [lianos/papers-bin#4]
Running under Mac OS X 10.8.2, I found that papers.py was unable to open the database. I tracked down the problem to the tilde character not being expanded in the definition of dbpath. The following patch solves the problem:

``` shell
--- papers.py.old   2013-03-04 14:43:05.000000000 +0100
+++ papers.py   2013-03-04 14:42:02.000000000 +0100
@@ -16,7 +16,7 @@

 ## You can overide these values in ~/.papersc
 DEFAULTS = {
-  'dbpath' : "~/Documents/Papers2/Library.papers2/Database.papersdb",
+  'dbpath' : os.path.expanduser("~/Documents/Papers2/Library.papers2/Database.papersdb"),
 }

 def filter_files(filelist):
```

**Comment by lianos** [comment]
I took your suggestion, but rather implemented the call to `os.path.expanduser` inside `Papers` object `__init__` so the fix is a bit more universal.

Thanks for the report and suggested fix!
